DROP TABLE IF EXISTS FEED_CFG.TWEETS;
DROP TABLE IF EXISTS FEED_CFG.OWNERSUBSCRIPTIONS;
DROP TABLE IF EXISTS FEED_CFG.USERSINFO;
CREATE TABLE USERSINFO(
    userid BIGINT NOT NULL PRIMARY KEY,
    login TEXT,
    name VARCHAR(500),
    surname VARCHAR(500)
) TABLESPACE feed_cfg_data;
CREATE TABLE TWEETS(
  tweetid BIGINT NOT NULL,
  userid BIGINT REFERENCES USERSINFO(userid),
  content TEXT,
  date TIMESTAMP,
  PRIMARY KEY(tweetid,userid)
) TABLESPACE feed_cfg_data;
CREATE TABLE OWNERSUBSCRIPTIONS(
    ownerid BIGINT NOT NULL,
    userid BIGINT REFERENCES USERSINFO(userid),
    PRIMARY KEY(ownerid,userid)
)