CREATE TABLE USERS
(
    ID LONG NOT NULL auto_increment,
    USERNAME NVARCHAR,
    EMAIL NVARCHAR,
    PASSWORD NVARCHAR,
    FIRST_NAME NVARCHAR,
    LAST_NAME NVARCHAR,
    STATUS NVARCHAR,
    CREATED DATETIME,
    UPDATED DATETIME
);